# permissions for end users to edit templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kumquat
    app.kubernetes.io/managed-by: kustomize
  name: template-editor-role
rules:
  - apiGroups:
      - kumquat.guidewire.com
    resources:
      - templates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kumquat.guidewire.com
    resources:
      - templates/status
    verbs:
      - get
